// Generated by gencpp from file my_robot_msgs/ResetCounter.msg
// DO NOT EDIT!


#ifndef MY_ROBOT_MSGS_MESSAGE_RESETCOUNTER_H
#define MY_ROBOT_MSGS_MESSAGE_RESETCOUNTER_H

#include <ros/service_traits.h>


#include <my_robot_msgs/ResetCounterRequest.h>
#include <my_robot_msgs/ResetCounterResponse.h>


namespace my_robot_msgs
{

struct ResetCounter
{

typedef ResetCounterRequest Request;
typedef ResetCounterResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ResetCounter
} // namespace my_robot_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::my_robot_msgs::ResetCounter > {
  static const char* value()
  {
    return "3b73bf1f76bcb54818883adc52048556";
  }

  static const char* value(const ::my_robot_msgs::ResetCounter&) { return value(); }
};

template<>
struct DataType< ::my_robot_msgs::ResetCounter > {
  static const char* value()
  {
    return "my_robot_msgs/ResetCounter";
  }

  static const char* value(const ::my_robot_msgs::ResetCounter&) { return value(); }
};


// service_traits::MD5Sum< ::my_robot_msgs::ResetCounterRequest> should match
// service_traits::MD5Sum< ::my_robot_msgs::ResetCounter >
template<>
struct MD5Sum< ::my_robot_msgs::ResetCounterRequest>
{
  static const char* value()
  {
    return MD5Sum< ::my_robot_msgs::ResetCounter >::value();
  }
  static const char* value(const ::my_robot_msgs::ResetCounterRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_robot_msgs::ResetCounterRequest> should match
// service_traits::DataType< ::my_robot_msgs::ResetCounter >
template<>
struct DataType< ::my_robot_msgs::ResetCounterRequest>
{
  static const char* value()
  {
    return DataType< ::my_robot_msgs::ResetCounter >::value();
  }
  static const char* value(const ::my_robot_msgs::ResetCounterRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::my_robot_msgs::ResetCounterResponse> should match
// service_traits::MD5Sum< ::my_robot_msgs::ResetCounter >
template<>
struct MD5Sum< ::my_robot_msgs::ResetCounterResponse>
{
  static const char* value()
  {
    return MD5Sum< ::my_robot_msgs::ResetCounter >::value();
  }
  static const char* value(const ::my_robot_msgs::ResetCounterResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_robot_msgs::ResetCounterResponse> should match
// service_traits::DataType< ::my_robot_msgs::ResetCounter >
template<>
struct DataType< ::my_robot_msgs::ResetCounterResponse>
{
  static const char* value()
  {
    return DataType< ::my_robot_msgs::ResetCounter >::value();
  }
  static const char* value(const ::my_robot_msgs::ResetCounterResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MY_ROBOT_MSGS_MESSAGE_RESETCOUNTER_H
