// Generated by gencpp from file my_robot_msgs/ResetCounterRequest.msg
// DO NOT EDIT!


#ifndef MY_ROBOT_MSGS_MESSAGE_RESETCOUNTERREQUEST_H
#define MY_ROBOT_MSGS_MESSAGE_RESETCOUNTERREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_robot_msgs
{
template <class ContainerAllocator>
struct ResetCounterRequest_
{
  typedef ResetCounterRequest_<ContainerAllocator> Type;

  ResetCounterRequest_()
    : reset_value(0)  {
    }
  ResetCounterRequest_(const ContainerAllocator& _alloc)
    : reset_value(0)  {
  (void)_alloc;
    }



   typedef int64_t _reset_value_type;
  _reset_value_type reset_value;





  typedef boost::shared_ptr< ::my_robot_msgs::ResetCounterRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_robot_msgs::ResetCounterRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ResetCounterRequest_

typedef ::my_robot_msgs::ResetCounterRequest_<std::allocator<void> > ResetCounterRequest;

typedef boost::shared_ptr< ::my_robot_msgs::ResetCounterRequest > ResetCounterRequestPtr;
typedef boost::shared_ptr< ::my_robot_msgs::ResetCounterRequest const> ResetCounterRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_robot_msgs::ResetCounterRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_robot_msgs::ResetCounterRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_robot_msgs::ResetCounterRequest_<ContainerAllocator1> & lhs, const ::my_robot_msgs::ResetCounterRequest_<ContainerAllocator2> & rhs)
{
  return lhs.reset_value == rhs.reset_value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_robot_msgs::ResetCounterRequest_<ContainerAllocator1> & lhs, const ::my_robot_msgs::ResetCounterRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_robot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_robot_msgs::ResetCounterRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_robot_msgs::ResetCounterRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_robot_msgs::ResetCounterRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_robot_msgs::ResetCounterRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_robot_msgs::ResetCounterRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_robot_msgs::ResetCounterRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_robot_msgs::ResetCounterRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "62f1c93d2d90b2a45f39aab680b0301c";
  }

  static const char* value(const ::my_robot_msgs::ResetCounterRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x62f1c93d2d90b2a4ULL;
  static const uint64_t static_value2 = 0x5f39aab680b0301cULL;
};

template<class ContainerAllocator>
struct DataType< ::my_robot_msgs::ResetCounterRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_robot_msgs/ResetCounterRequest";
  }

  static const char* value(const ::my_robot_msgs::ResetCounterRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_robot_msgs::ResetCounterRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 reset_value\n"
;
  }

  static const char* value(const ::my_robot_msgs::ResetCounterRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_robot_msgs::ResetCounterRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.reset_value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ResetCounterRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_robot_msgs::ResetCounterRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_robot_msgs::ResetCounterRequest_<ContainerAllocator>& v)
  {
    s << indent << "reset_value: ";
    Printer<int64_t>::stream(s, indent + "  ", v.reset_value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_ROBOT_MSGS_MESSAGE_RESETCOUNTERREQUEST_H
